### ISSUE TITLE
It's not compatible with Tfs2017 U1

### ISSUE THREAD

**Issue by DomenicoFerrari** [figueiredorui/1-click-child-links#14]
I've tried to install plugin on Tfs2017.Update1 (version 15.112.26307.0) but has failed with this message: VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

**Comment by nschonni** [comment]
This sounds like you double-clicked on the VSIX on windows rather than inistalling the extension into TFS.
EX: from the newer gallery download page

>Your download has started!
To install "1-Click Child-Links" on Team Foundation Server, perform following steps:
Navigate to the Team Foundation Server Extensions page on your server.
(For example, http://someserver:8080/tfs/_gallery/manage)
Click upload new extension and select the file you have just downloaded.
After the extension has successfully uploaded, click Install and select the Team Project Collection to install into.
