### ISSUE TITLE
Using 1-Click Child-Links from the menu does not add links

### ISSUE THREAD

**Issue by MitkoCA** [figueiredorui/1-click-child-links#19]
I installed the extension on TFS 2017 RTW (corporate on-premises deployment) and tried to use it - created templates and clicked the 1-Click Child-Links when creating work item. No links are being created. Read the guide on Marketplace multiple times, but could not figure out what I am missing.
Would you be able to point out what step I am missing?

**Comment by mevanecek** [comment]
I see the same behavior in VSTS, using either User Story or Product Backlog Item. Clicking the 1-Click Child menu item does not have any effect on the open work item.

**Comment by figueiredorui** [comment]
@MitkoCA, @mevanecek do you see console errors regarding 1-Click Child-Links extension?

**Comment by rprouse** [comment]
It is working for me in VSTS.  If it isn't working for you, make sure that templates are setup for the team you are in. Templates are scoped to a team, so you need to make sure you set them up for all teams. We made that mistake 😄

**Comment by rprouse** [comment]
This wasn't working for a co-worker today. It turned out that she was using Internet Explorer, switching to Firefox or Chrome worked for her. She was sharing her screen, so I had her open up dev tools in IE and I captured the error in the console,

![image](https://user-images.githubusercontent.com/493828/35169253-e437efac-fd29-11e7-9a4e-53d8f5de78b6.png)

**Comment by pabrams** [comment]
This happens in almost every TFS web extension.  Need to add a polyfill if you want to support IE.
