### ISSUE TITLE
JSON string in child template's description field does not work

### ISSUE THREAD

**Issue by MrLaffel** [figueiredorui/1-click-child-links#46]
We have a set of wonderful templates, that we'd like to be created based on parent tagging like this:

{
    "applywhen": [
    {
        "System.Tags" : ["Android"],
        "System.WorkItemType": "Bug"
    }]
}

However, the extension does not pick it up. If I use the simple version and just write [Bug] in the template description it works (albeit not taking the tag "Android" into consideration)

The string I have in the template description is compressed to tihs: {"applywhen":[{"System.Tags":["Android"],"System.WorkItemType":"Bug"}]}

What am I doing wrong?

**Comment by MrLaffel** [comment]
I've done some experimenting, and having the string like this: {"applywhen":[{"System.Tags":"Android","System.WorkItemType":"Bug"}]} it seems to work. But if I spice it up like this {"applywhen":[{"System.Tags":"Android"},{"System.Tags":["Android","iOS"]}]} it stops working all together and I can't figure out why.

**Comment by mpburtt** [comment]
I've found the same problem, if you use a list of Tag values then the template is ignored even if the parent work item matches all of those tags.
The same problem happens if you have a parent work item with multiple tags and your apply-when filter is only looking for one of them. For example, if my JSON description is {"applywhen":[{"System.Tags":"Android","System.WorkItemType":"Bug"}]} and the parent bug has the tags "Android" and "iOS" then the template is ignored.

**Comment by figueiredorui** [comment]
Fixed on v0.11.1
